#!/bin/bash
# chkconfig: 2345 20 80
# description: Spooch server

# Source function library.
. /etc/init.d/functions

start() {
    echo -n $"Starting Spooch server:"
    /usr/local/bin/spooch start
    echo ""
    return 0
}

stop() {
    echo -n $"Stopping Spooch server:"
    /usr/local/bin/spooch stop
    echo ""
    return 0
}

case "$1" in 
 start)
     start
     ;;
 stop)
     stop
     ;;
 retart)
     stop
     start
     ;;
 *)
      echo "Usage: $0 {start|stop|restart}"
esac

exit $RETVAL